.TH simple-image-filter 1  "September 15, 2021" "version 1" "General Commands Manual"

.SH NAME
simple\-image\-filter \-  Image Filter 

.SH SYNOPSIS
.B simple\-image\-filter

.SH DESCRIPTION
.B Image Filter 
is an image processing software, can handle image rotation, clip, basic beautification, filter and other graph functions.

.SH OPTIONS
.PP
This program does not accept any command line options.

.PP
This manual page was written by
.MT dluyaning@\:gmail.com
 Lu YaNing
.ME
for the Debian project (and may be used by others).
